---
title: "Assignments"
---

There are two main forms of assignments in the SURE 2023 program, namely:

  - Demo-labs
  - Final research project, poster, and presentation

Some additional details on both are provided below.

## Demo-labs

We also provide you demo-lab materials for you to test out your understanding of
the course content. They are usually released once or twice a week, as per the
[schedule](../schedule.qmd). Completing these demo-labs is strongly recommended
to help you reinforce the material. There is no grading involved here, just
learning. So don't hesitate to reach out to your fellow peers, TA Advisors, and
course instructors for help.

### Viewing demo labs (in your browser)

You can view all demo lab materials in your browser (e.g., Chrome/Firefox) by
navigating the links in the left sidebar, under the 'Demo Lab' dropdown header,
or via the [schedule](../schedule.qmd).

### Downloading demo labs (on your laptop)

You can also download the RMarkdown (`.Rmd`) demo-lab files using the 
convenient links below:

::: {.callout appearance="minimal"}
Download **Demo Lab 1 (Intro to `R`):** 

{{\< downloadthis _files/demo-labs/demo-lab-01.Rmd
dname="demo-lab-01" label="demo-lab-01.Rmd" icon="file-earmark"
type="success" \>}}

Download **Demo Lab 2 (data wrangling with `dplyr`):** 

{{\< downloadthis _files/demo-labs/demo-lab-02.Rmd
dname="demo-lab-02" label="demo-lab-02.Rmd" icon="file-earmark"
type="success" \>}} 
{{\< downloadthis _files/demo-labs/demo-lab-02-supp.zip
dname="demo-lab-02-supp" label="demo-lab-02-supp.zip" icon="file-earmark"
type="success" \>}}

Download **EDA Mini Project 1 (Requirements and Data):** 

{{\< downloadthis _files/mini-projects/mini-project-01.Rmd
dname="mini-project-01" label="mini-project-01.Rmd" icon="file-earmark"
type="success" \>}}

Download **Demo Lab 3 (Data visualization practice with `ggplot`):** 

{{\< downloadthis _files/demo-labs/demo-lab-03.Rmd
dname="demo-lab-03" label="demo-lab-03.Rmd" icon="file-earmark"
type="success" \>}} 

Download **Demo Lab 4 (Exploratory Data Analysis (Case Studies)):** 

{{\< downloadthis _files/demo-labs/demo-lab-04.Rmd
dname="demo-lab-04" label="demo-lab-04.Rmd" icon="file-earmark"
type="success" \>}} 

Download **Demo Lab 5 (Clustering):** 

{{\< downloadthis _files/demo-labs/demo-lab-05.Rmd
dname="demo-lab-05" label="demo-lab-05.Rmd" icon="file-earmark"
type="success" \>}} 

Download **Demo Lab 6 (Linear Regression):** 

{{\< downloadthis _files/demo-labs/demo-lab-06.Rmd
dname="demo-lab-06" label="demo-lab-06.Rmd" icon="file-earmark"
type="success" \>}} 
:::

## Research project deliverables

As noted in our [syllabus](../syllabus.qmd) and [schedule](../schedule.qmd) the
**only deliverables** you have are your **final (Optum or CMSAC) research 
project report, poster, and presentation**. 

::: {.callout-tip}
### Research project deliverables

We reemphasize that the research project won't be formally graded. However
**your three research deliverables will be presented by you to various important
(executive) stakeholders** in healthcare (Optum) and the sports (CMSAC) data
science community.

So it is in your best interest to put your best foot forward, since it will be
of **great benefit for your future data science career**!
:::

You can view all assignment materials by navigating the links in the left 
sidebar, or via the [schedule](../schedule.qmd).


