project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"
  preview:
    port: 3333

execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/readings.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Explore cutting-edge statistics and data science methodology with applications in sports and health analytics"

website:
  # image: "/files/cmu-statds-icon-hex-2-bg.png"
  title: "SURE 2023"
  site-url: "https://cmu-sure-2023.netlify.app/"

  favicon: "/files/cmu-statds-icon-hex-2-bg.png"

  twitter-card:
    image: "/files/cmu-statds-icon-hex-2-bg.png"
    card-style: summary_large_image
    creator: "@CMU_Stats"

  open-graph:
    image: "/files/cmu-statds-icon-hex-2-bg.png"
    locale: en_US

  navbar:
    logo: "/files/cmu-statds-icon-hex-2-bg.png"
    logo-alt: "SURE 2023 logo."
    pinned: true
    background: "#341648"
    right:
      - href: people.qmd
        text: Team
      - syllabus.qmd
      - schedule.qmd
      - text: "Lectures"
        file: class/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Guides"
        menu:
          - text: "SURE 2023 Computing Setup"
          - file: guides/computing-setup.qmd
          - text: "SURE 2023 Pittsburgh Resources"
          - file: guides/pittsburgh-student-resources.qmd
          - text: "SURE 2023 Exploring Pittsburgh"
          - file: guides/pittsburgh-fun-activities.qmd
          - text: "SURE 2023 Website Credits"
          - file: credits.qmd
      - icon: slack
        href: "https://cmu-sure-2023.slack.com"
        aria-label: Slack

  sidebar:
    - title: "Classes"
      style: "docked"
      search: false
      background: light
      contents:
        - section: "Overview"
          contents:
            - class/index.qmd
        - section: "Data Engineering Lectures"
          contents:
            - section: "UNIX"
              contents:
                - text: "1: Getting acquainted with the UNIX philosophy"
                  file: data_eng/01-class-data-eng.qmd
                - text: "2: Getting comfortable with the UNIX philosophy"
                  file: data_eng/02-class-data-eng.qmd
        - section: "Data Science Lectures"
          contents:
            - section: "Orientation"
              contents:
                - text: "1: Welcome to SURE 2023"
                  file: class/01-class.qmd
            - section: "Exploratory Data Analysis"
              contents:
                - text: "2: Exploring Data: Into the tidyverse"
                  file: class/02-class.qmd
                - text: "3: The grammar of graphics and ggplot2"
                  file: class/03-class.qmd
                - text: "4: Visualizing 1D categorical and continuous variables"
                  file: class/04-class.qmd
                - text: "5: Visualizing 2D categorical and continuous by categorical"
                  file: class/05-class.qmd
                - text: "6: Density estimation"
                  file: class/06-class.qmd
                - text: "10: Visualizing Geographic Data"
                  file: class/10-class.qmd
            - section: "Clustering"
              contents:
                - text: "7: K-means"
                  file: class/07-class.qmd
                - text: "8: Hierarchical clustering"
                  file: class/08-class.qmd
                - text: "9: Gaussian mixture models"
                  file: class/09-class.qmd
            - section: "Presentation Skills"
              contents:
                - text: "12: Working with xaringan and xaringanthemer"
                  file: class/12-class.qmd
            - section: "Machine Learning"
              contents:
                - text: "11: Model assessment vs selection"
                  file: class/11-class.qmd
                - text: "13: Linear regression"
                  file: class/13-class.qmd
                - text: "14: Intro to variable selection"
                  file: class/14-class.qmd
                - text: "15: Regularization"
                  file: class/15-class.qmd
                - text: "16: Tidymodels"
                  file: class/16-class.qmd
                - text: "17: GLMs"
                  file: class/17-class.qmd
                - text: "18: Logistic regression"
                  file: class/18-class.qmd
                - text: "19: K-Nearest Neighbors Regression and Classification"
                  file: class/19-class.qmd
                - text: "20: Decision Trees"
                  file: class/20-class.qmd
            #     - text: "23: Random Forest and Gradient-Boosted trees"
            #       file: class/23-class.qmd

    - title: "Documentation"
      contents:
        - section: "Syllabus"
          contents:
            - syllabus.qmd
        - section: "Code of Conduct"
          contents:
            - code-of-conduct.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Demo Labs"
          contents:
            - text: "Demo Lab 1: Intro to R"
              file: assignment/demo-lab-01.qmd
            - text: "Demo Lab 2: Data wrangling with dplyr"
              file: assignment/demo-lab-02.qmd
            - text: "Demo Lab 3: Data visualization practice with ggplot"
              file: assignment/demo-lab-03.qmd
            - text: "Demo Lab 4: Exploratory Data Analysis"
              file: assignment/demo-lab-04.qmd
            - text: "Demo Lab 5: Clustering"
              file: assignment/demo-lab-05.qmd
            - text: "Demo Lab 6: Linear Regression"
              file: assignment/demo-lab-06.qmd
        - section: "CMSAC Mini projects"
          contents:
            - text: "EDA Mini-Project 1: Requirements and Data"
              file: assignment/mini-project-01.qmd
        - section: "Final projects"
          contents:
            - text: "Optum Research Project Specification"
              file: assignment/optum-project-guidelines.qmd
            - text: "SURE 2023 Report Writing Guideline"
              file: assignment/report-writing-guideline.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var university.name >}}]({{< var university.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      With {{< fa solid heart >}} to our [Website Credits](/credits.qmd)

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
