project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"
  preview:
    port: 3333

execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/readings.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Explore how the public and nonprofit sectors work around the world and learn how political institutions shape government and civil society"

website:
  title: "CMU SURE Program 2023"
  site-url: "https://compasp23.classes.andrewheiss.com"

  favicon: "/files/.pngcmu-statds-icon-hex-2"

  twitter-card:
    image: "/files/cmu-statds-icon-hex-2.png"
    card-style: summary_large_image
    creator: "@andrewheiss"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/cmu-statds-icon-hex-2.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#341648"
    # left:
    #   - href: people.qmd
    #     text: People
    right:
      - href: people.qmd
        text: Team
      - syllabus.qmd
      - schedule.qmd
      - text: "Lectures"
        file: class/index.qmd
      - text: "Labs and Projects"
        file: assignment/index.qmd
      - icon: slack
        href: "https://cmu-sure-2023.slack.com"
        aria-label: Slack

  sidebar:
    - title: "Classes"
      style: "docked"
      search: false
      background: light
      contents:
        - section: "Overview"
          contents:
            - class/index.qmd
        - section: "Classes"
          contents:
            - section: "Orientation"
              contents:
                - text: "1: Welcome to SURE 2023"
                  file: class/01-class.qmd
            - section: "Exploratory Data Analysis"
              contents:
                - text: "2: Exploring Data: Into the tidyverse"
                  file: class/01-class.qmd
                - text: "3: The grammar of graphics and ggplot2"
                  file: class/03-class.qmd
                - text: "4: Visualizing 1D categorical and continuous variables"
                  file: class/04-class.qmd
                - text: "5: Visualizing 2D categorical and continuous by categorical variables"
                  file: class/05-class.qmd
                - text: "6: Density estimation"
                  file: class/06-class.qmd
                # - text: "6: Geographical EDA using Shapefiles"
                #   file: class/06-class.qmd
            - section: "Clustering"
              contents:
                - text: "7: K-means"
                  file: class/07-class.qmd
                - text: "8: Hierarchical clustering"
                  file: class/08-class.qmd
                - text: "9: Gaussian mixture models"
                  file: class/09-class.qmd
            - section: "Presentation Skills"
              contents:
                - text: "10: Working with xaringan and xaringanthemer"
                  file: class/10-class.qmd
            - section: "Machine Learning"
              contents:
                - text: "11: Model assessment vs selection"
                  file: class/11-class.qmd
                - text: "12: Linear regression"
                  file: class/12-class.qmd
                - text: "13: Intro to variable selection"
                  file: class/13-class.qmd
                - text: "14: Regularization"
                  file: class/14-class.qmd
                - text: "15: Tidymodels"
                  file: class/15-class.qmd
                - text: "16: Dimension reduction: PCA"
                  file: class/16-class.qmd
                - text: "17: PCR and PLS"
                  file: class/17-class.qmd
                - text: "18: GLMs"
                  file: class/18-class.qmd
                - text: "19: Logistic regression"
                  file: class/19-class.qmd
                - text: "20: GAMs"
                  file: class/20-class.qmd
                - text: "21: Decision Trees"
                  file: class/21-class.qmd
                - text: "22: Random Forest and Gradient-Boosted trees"
                  file: class/22-class.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Final project"
          contents:
            - assignment/policy-brief.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var university.name >}}]({{< var university.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
