---
title: "Code of Conduct"
---

Students participating in our Summer Undergraduate Research Experience
(SURE) here at [[Carnegie
Mellon]{.underline}](https://www.cmu.edu/student-affairs/theword/code/index.html#:~:text=These%20standards%20require%20personal%20integrity,must%20be%20met%2C%20commitments%20kept)
are to consider themselves part of the Carnegie Mellon academic
community and are expected to meet and maintain the highest personal and
professional ethics and conduct.

We are committed to cultivating a transformative and educational
experience, as well as safeguarding personal health and well-being. We
require students to act with personal and intellectual integrity, to
speak honestly, and to treat themselves and others with the utmost
respect.

Students participating in the program are expected to:

-   Respect the rights of your instructors, assistants and other staff,
    as well as your peers

-   Promote the health and safety of all members of our diverse
    community

-   Treat others with honesty and fairness

-   Participate in the program with the highest level of professionalism
    and motivation to learn

-   Respect the property of others as well as that of Carnegie Mellon

-   Understand and abide by all [[Carnegie Mellon community
    standards]{.underline}](https://www.cmu.edu/student-affairs/theword/index.html#community)
    as well as all local, state, and federal laws

-   Attend, be on time for, and actively participate in all program
    sessions.

All participating students are expected to have timely attendance and to
participate in all mandatory program sessions, including all in-person,
virtual, and group activities. All students are expected to be present,
prepared, and ready to actively engage in each session. Student
engagement is central to the program and pivotal to the overall success
of the summer experience.

-   If you believe you will need to be absent for an upcoming session
    for any reason (illness, personal reasons, etc.), you will need to
    contact your Summer Program Director and Program Advisor as
    proactively as possible to communicate any potential absences.

-   **Please note**: extended and/or unexcused absences may incur
    potential consequences, up to and including dismissal from the
    program and the termination of your stipend

The Statistics & Data Science department and Carnegie Mellon prohibits
conduct that creates a hostile environment for faculty, staff, students,
or other parties. Examples include:

-   Disrespect toward an instructor, peer, or other members of the
    Statistics & Data Science community

-   Abusive, intimidating, hostile or obscene language, gestures, or
    behavior

-   Any kind of [[discrimination or
    harassment]{.underline}](https://www.cmu.edu/policies/forms-and-documents/soa-violations.pdf)
    that would create a hostile or abusive environment for any member
    of our community

-   Any kind of unwelcome coercive, exploitive, or other forms of
    [[prohibited sexual
    misconduct]{.underline}](https://www.cmu.edu/policies/administrative-and-governance/sexual-misconduct/policy-statement.html)

Any form of sexual misconduct will **not be tolerated** by the program.
All participating students are expected to read and become familiar with
Carnegie Mellon's [[sexual misconduct
policies]{.underline}](https://www.cmu.edu/policies/administrative-and-governance/sexual-misconduct/policy-statement.html)
and will be expected to abide by them beginning the your first day here.
All students are subject to CMU's [[Title IX
office]{.underline}](https://www.cmu.edu/title-ix/) policies and
procedures as well as any related potential disciplinary action.

If students need any kind of support or assistance during their time
here, please contact one of the following SURE coordinators:

- Glenn Clune: SURE Academic Advisor</br>
  Email:
  [[gclune@andrew.cmu.edu]{.underline}](mailto:gclune@andrew.cmu.edu)</br>
  Office Location: Baker Hall 132L</br>
  In office: Monday & Tuesday

- Teraya White: SURE Academic Advisor</br>
  Email:
  [[terayaw@andrew.cmu.edu]{.underline}](mailto:terayaw@andrew.cmu.edu)

- Jamie McGovern: SURE Program Director</br>
  Email:
  [[jamiemcg@andrew.cmu.edu]{.underline}](mailto:jamiemcg@andrew.cmu.edu)

When all members of the community uphold these values, we are able to
provide a formative and collaborative experience for all summer program
participants.
