---
title: "Pittsburgh-based resources"
---

::: {.callout-tip}
### A friendly note from your friendly Academic Advisor [Glenn](/people/student_support/clune-glenn.qmd)

Welcome to Pittsburgh! This fantastic city will be your home for the
next two months, and we want to make sure you have access to any support
systems you may need during that time. We hope that you'll be able to
get everything possible out of the SURE program, so these resources
should help alleviate any stress that could arise elsewhere. We've
collated the following list of Pittsburgh-based resources to assist you,
should you have need during the program.

--Glenn
:::

## Sponsored CMU ID

A [[CMU sponsored
ID]{.underline}](https://www.cmu.edu/idplus/idcards/sponsored.html) is
an optional, additional expense for students that can provide the
following:

-   General building access

-   Fitness Center Access (classes not included)

-   Library access & borrowing of books

-   CMU campus shuttles & escort services

    -   Please note that Pittsburgh Bus Transit is not included

## Pittsburgh Bus/Transit Pass

If you would like to utilize public transit to get from your program
housing to campus, or to explore what Pittsburgh has to offer, please
see the below links for more information:

-   [[Current Bus
    Fares]{.underline}](https://www.rideprt.org/fares-and-passes/fare-information/)

-   [[Getting a bus/fare
    pass]{.underline}](https://www.rideprt.org/fares-and-passes/connectcard/)

-   Personally, I recommend both [[Google
    Maps]{.underline}](https://www.google.com/maps/place/Posner+Hall,+Pittsburgh,+PA+15213/@40.4410403,-79.9448752,17z/data=!3m1!4b1!4m6!3m5!1s0x8834f220254d5285:0xdadf79d8b1c0495c!8m2!3d40.4410403!4d-79.9422949!16s%2Fm%2F040_67y?entry=ttu)
    (for optimal mapping and outlining of routes) and the [[Transit
    app]{.underline}](https://transitapp.com/) (for real-time tracking
    of busses) to coordinate bus plans

## Medical/Wellness Resources

If you find yourself in need of physical, mental, or emotional
attention, please utilize these local institutions for assistance:

-   [[UPMC Urgent Care
    Shadyside]{.underline}](https://www.upmc.com/services/urgent-care/locations/shadyside)

    -   5231 Centre Ave, Pittsburgh, PA 15232

    -   412-623-4114

-   [[UPMC Presbyterian
    Hospital]{.underline}](https://www.upmc.com/locations/hospitals/presbyterian?utm_source=google&utm_campaign=business-profile&utm_content=upmcpresbyterian-pittsburgh-website)

    -   200 Lothrop St, Pittsburgh, PA 15213

    -   412-755-2307

-   [[Allegheny Health Network Emergency Care
    Brentwood]{.underline}](https://www.ahnneighborhood.org/locations/brentwood/)

    -   3290 Saw Mill Run Blvd, Brentwood, PA 15227

-   [[Resolve Crisis
    Services]{.underline}](https://www.upmc.com/services/behavioral-health/resolve-crisis-services)

    -   333 North Braddock Ave, Pittsburgh, PA 15213

    -   1-888-796-8226

-   [[Allies for Health and
    Well-Being]{.underline}](https://www.lgbtq.pitt.edu/find-support/local-resources)

    -   Medical support and community-based resources for individuals
        living with or at risk for HIV, viral hepatitis, and other
        sexually transmitted infections

    -   Local support and resources for members of the LGBTQ community

## Food Insecurity

If you find yourself struggling with having enough food to get through
your time here, please contact the following resource for assistance:

-   [[Greater Pittsburgh Community Food
    Bank]{.underline}](https://pittsburghfoodbank.org/find-food/get-help/)
    412-460-3663 ext. 655

## Finding a Faith Community

If you are part of a religious community and want to find a local
community during your

time here, please use the following resource to find a faith community:

-   [[CMU Council of Religious
    Advisors]{.underline}](https://www.cmu.edu/wellbeing/about-us/cora.html)
