---
title: "Fun activities to do in Pittsburgh"
---

::: {.callout-tip}
### A friendly note from your friendly co-instructor [Meg](/people/staff/ellingwood-meg.qmd)

Pittsburgh gets a bad rap, but I've found it to be a really fun, active, vibrant
city! To that end, as an instructor I want you to get the most out of this
program, both academically and personally, so I've compiled a list of fun
activities that you could try if you find yourself bored in the evenings or on
the weekends. Note that it may be a bit biased. I haven't tried/visited each of
these things, but the ones I haven't done myself still come highly recommended
from friends in town. I hope you can get out there and do some cool stuff!

--Meg
:::

# If you're into sports

Pittsburgh sports are awesome (regardless of how well the teams may or
may not be doing in their respective seasons...). It's a big deal here.
Also, fun fact, the city requires all professional teams to have Black &
Gold as their colors.

-   [Pittsburgh Pirates (MLB)](https://www.mlb.com/pirates)

    -   Arguably one of the most beautiful stadium views in baseball
        (looks out over downtown PGH)

    -   Tickets usually quite accessible, compared to other MLB teams,
        can be found
        [[here]{.underline}](https://www.mlb.com/pirates/tickets/single-game-tickets)

-   [Pittsburgh Riverhounds SC](https://www.riverhounds.com/) (USL Championship)

    -   First-tier experience for second-tier prices, find tickets
        [[here]{.underline}](https://www.riverhounds.com/tickets/)

-   [Pittsburgh Steelers](https://www.steelers.com/) (NFL, out of season)

-   [Pittsburgh Penguins](https://www.steelers.com/) (NHL, out of season)

# If you love nature

-   [Phipps Conservatory](https://www.phipps.conservatory.org/)

    -   Beautiful botanical gardens just a stone's throw away from
        campus

    -   Lots of cool events, see the
        [[website]{.underline}](https://www.phipps.conservatory.org/)
        for details

-   [Frick Park](https://pittsburghparks.org/explore-your-parks/regional-parks/frick-park/)

    -   Fantastic walking/running trails, great hammock spots

    -   Honestly feels like you've escaped to the wilderness but you're
        still [[in
        Pittsburgh]{.underline}](https://pittsburghparks.org/explore-your-parks/regional-parks/frick-park/)

-   [Schenley Park](https://pittsburghparks.org/explore-your-parks/regional-parks/schenley-park/)

    -   Even [[closer to
        campus]{.underline}](https://pittsburghparks.org/explore-your-parks/regional-parks/schenley-park/)
        than Frick, somewhat smaller but equally beautiful

    -   The sunset over [[Flagstaff
        Hill]{.underline}](https://www.google.com/maps/place/Flagstaff+Hill/@40.4401509,-79.9453002,15z/data=!4m6!3m5!1s0x8834f2209a841261:0x86b40a8b4c86e782!8m2!3d40.4401509!4d-79.9453002!16s%2Fg%2F11h8jpjvvm?entry=ttu)
        is just \*chef's kiss\*

-   [Three Rivers Heritage Trail](https://friendsoftheriverfront.org/three-rivers-heritage-trail/)

    -   [[Paved
        trail]{.underline}](https://friendsoftheriverfront.org/three-rivers-heritage-trail/)
        for walking/running/biking

    -   Can be accessed from various points around the city, I usually
        go to the [[Southside Riverfront
        Park]{.underline}](https://www.google.com/search?tbs=lf:1,lf_ui:1&tbm=lcl&q=southside+riverfront+park&rflfq=1&num=10&rldimm=3910747117372124980&ved=2ahUKEwiut6-O7KL_AhVjFlkFHaeMBx0Qu9QIegQIEhAK#rlfi=hd:;si:3910747117372124980;mv:%5B%5B40.4316197,-79.96438429999999%5D,%5B40.4290142,-79.97263079999999%5D%5D;tbs:lrf:!1m4!1u2!2m2!2m1!1e1!2m1!1e2!3sIAE,lf:1,lf_ui:1)
        for long runs

# If you like culture

-   [Carnegie Library](https://www.carnegielibrary.org/)

    -   A [[whole
        network]{.underline}](https://www.carnegielibrary.org/) of
        libraries across the city, but it's main location is at the
        Museum on Forbes (see below)

    -   Lots of events available, and just a cool spot

-   [Carnegie Museum](https://carnegiemuseums.org/)

    -   Actually [[four
        museums]{.underline}](https://carnegiemuseums.org/), including
        the Museum of Art, Museum of Natural History, Science Center,
        and the Andy Warhol Museum

    -   I can personally vouch for the Science Center being really fun,
        but I've heard the others are quite cool as well, and a few of
        them are walking distance from campus

-   __Various festivals__

    -   You can find a list of annual events
        [[here]{.underline}](https://www.visitpittsburgh.com/events-festivals/annual-events/)--
        Picklesburgh is a personal favorite!

    -   There are also plenty of nice [[farmers
        markets]{.underline}](https://pittsburghpa.gov/events/farmers-market)
        to [[check
        out]{.underline}](https://bloomfieldpgh.org/bloomfield-saturday-market/)

# Generally cool areas to explore

-   [Strip District](https://www.visitpittsburgh.com/neighborhoods/strip-district/)

    -   Specialty grocery stores (Korean, Mexican, Italian, etc.)

    -   Restaurants, coffee shops, various other [[food-related
        activities]{.underline}](https://www.discovertheburgh.com/strip-district-guide/)

-   [Downtown](https://downtownpittsburgh.com/visit/) (Dahntahn)

    -   [[Point State
        Park]{.underline}](https://www.dcnr.pa.gov/StateParks/FindAPark/PointStatePark/pages/default.aspx)
        sits at the confluence of the Allegheny and Monongahela

    -   The [[Duquesne
        Incline]{.underline}](http://www.duquesneincline.org/) is a
        classic Pittsburgh tourist activity

-   Lawrenceville (Butler St.), Shadyside (Walnut St.), Squirrel Hill
    (Murray Ave)

    -   Neighborhoods with some nice shopping/restaurant areas

-   Some restaurants that I recommend (again, biased, not exhaustive)

    -   [[Kiin Lao]{.underline}](https://www.kiinpgh.com/) (prev.
        Bangkok Balcony, Squirrel Hill)

    -   [[Udipi]{.underline}](https://www.google.com/maps/place/Udipi+Cafe/@40.4435628,-79.7916474,15.07z/data=!4m6!3m5!1s0x8834ebcbd5a5bdf7:0xa3e51660ee167bc8!8m2!3d40.4434096!4d-79.7905167!16s%2Fg%2F1th5_g2z?entry=ttu)
        (Monroeville, very far but so delicious, no online presence
        whatsoever)

    -   [[Stack'd]{.underline}](https://www.google.com/maps/place/Stack'd+Oakland/@40.4413253,-79.9568899,15z/data=!4m6!3m5!1s0x8834f229c2648db9:0xd9c0693a0be9ab5d!8m2!3d40.4413253!4d-79.9568899!16s%2Fg%2F11bwytt_h7?entry=ttu)
        (Oakland, custom burgers, very close to campus)

    -   [[Iron Born Pizza]{.underline}](https://ironbornpizza.com/)
        (Detroit-style, which I did not know existed, good delivery
        option)
